added more info when check formatting style fails

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,14 @@ jobs:
       - name: Check Java Code Formatting Style
         run: |
           curl -L -s -o google-java-format.jar https://github.com/google/google-java-format/releases/download/v1.35.0/google-java-format-1.35.0-all-deps.jar
-          find src/ -name "*.java" | xargs java -jar google-java-format.jar --set-exit-if-changed --dry-run
+
+          if ! find src/ -name "*.java" | xargs java -jar google-java-format.jar --set-exit-if-changed --dry-run; then
+            echo "==================================================="
+            echo " [FAIL] Style guide mismatch detected."
+            echo " Please run 'ci.bat' locally to check for more detail."
+            echo "==================================================="
+            exit 1
+          fi
 
       # 4. Compile the application with Ant
       - name: Build JAR with Ant
